### ISSUE TITLE
Download links do not work

### ISSUE THREAD

**Issue by unixpickle** [piergiaj/AViD#2]
When I try to download the dataset from Drive, I see:

![image](https://user-images.githubusercontent.com/406021/87447537-b2ac7880-c5c8-11ea-95da-a58daccc16ef.png)

Google Drive seems like a bad place to store files for people to download. Some alternatives that I've seen:

 * Dropbox
 * GCS (Google Cloud Storage)
 * AWS (Amazon Web Storage)
 * bitTorrent (crowdsource the dataset distribution!)

**Comment by piergiaj** [comment]
Thanks for bringing this to our attention. We are working on alternative links, hopefully within a few hours.

**Comment by piergiaj** [comment]
Here's new links for the resized clips, uploading on the original full resolution currently.
[AViD_small_part1](https://indiana-my.sharepoint.com/:u:/g/personal/ajpiergi_iu_edu/EQJy9LbYiHROumzQbul9vCsBsYFyHtGIvtwnpFhjmFtIaQ?e=QRP2LR) 

[AViD_small_part2](https://indiana-my.sharepoint.com/:u:/g/personal/ajpiergi_iu_edu/EQ-z8s-6c7JMlA657mP6EYQBuFKB4vzqqShuVeUsPxB5ow?e=FvZPvG) 

[AViD_small_part3](https://indiana-my.sharepoint.com/:u:/g/personal/ajpiergi_iu_edu/Ea-WGKwTTzhNr4wTl3LhaHABQZ1TwptVCq_f_3QSuGoK1w?e=vRS5Zo)

**Comment by unixpickle** [comment]
I am having trouble obtaining the dataset from these new download links. I downloaded the files successfully, but when I concatenate them and then gunzip and untar, I see decompression errors after about 200K files (which I assume is roughly the size of part 1):

```
gunzip: invalid compressed data--crc error
gunzip: avid.tar.gz: uncompress failed
```

For the three parts, here are the md5 checksums I see, as well as the file sizes:

 * part 1: `md5=3c2fd0dde60b86ecea664af34cd860e8` (95000000000 bytes)
 * part 2: `md5=913567cd29e5ae1d425e73c0c7fc13c1` (95000000000 bytes)
 * part 3: `md5=b45a7c15b02b476aea081691cc6da9c1` (29470942061 bytes)

Let me know if my files somehow got corrupted, or if I am unzipping incorrectly.

**Comment by piergiaj** [comment]
I used split to create the files, so using:
cat avid_small.tar.gz.parta* >avid.tar.gz
then
tar -xzvf avid.tar.gz

should extract everything.

shouold work. Those checksums look correct to me.

**Comment by unixpickle** [comment]
When I run the command you showed, I get:

```
...
tar: Damaged tar archive
tar: Retrying...
tar: Tar entry size overflow
tar: Error exit delayed from previous errors.
```

Running `ls -l | wc -l` after this error yields `198241`.

**Comment by piergiaj** [comment]
try this version: https://aviddataset.blob.core.windows.net/avid/avid_small.tar.gz

**Comment by unixpickle** [comment]
I managed to download that file. Haven't gotten a chance to extract it yet. Here's what I see so far:

 * md5 hash of the file is `fc99d39eab670a18551fa1bc16e233af`.
 * size is exactly `219470942061` bytes (matches three parts added together from before).
 * md5 hash of the three parts I downloaded before, concatenated, is `9c00910bb2f9bac632d355fb5f4df7d3`. This differs from the above checksum.

**Comment by piergiaj** [comment]
Great, hopefully it extracts (it should, it is identical to the drive and my local version). Maybe one of those 3 got corrupted during the split or I split it wrong.

**Comment by unixpickle** [comment]
It extracted without any problems. Thanks so much!

**Comment by unixpickle** [comment]
Going to close this issue since I have verified that the new download link works.
